teste=input('Digite algo: ')
print('O que voce digitou e numerico?', teste.isnumeric())
print('O que voce digitou e alfanumerico?', teste.isalnum())
print('O que voce digitou tem somente letras?', teste.isalpha())
print('O que voce digitou esta em minusculo?', teste.islower())
print('O que voce digitou esta em maiusculo?', teste.isupper())
print('O que voce digitou e um digito?', teste.isdigit())
print('O que voce digitou e um espaco vazio?', teste.isspace())
print('O que voce digitou e um numero decimal?', teste.isdecimal())
print('O que voce digitou e printavel?', teste.isprintable())
print('O que voce digitou e um titulo?(primeira letra maiuscula e o restante minuscula)', teste.istitle())
